# 带[ ]括号的，就是多选，不带的就是单选
boss:
  sayHi: "拥有某行业新型独角兽核心部门开发经验，25届信息与计算科学本科(科班一本）；熟悉大部分Java,golang技术栈以及多种语言基础，并且涉猎云原生相关知识，爱好查阅博客学习相关技术，并且有自己的博客，详情可以查看我的简历，希望贵司给予机会。" #必须要关闭boss的自动打招呼
  keywords: ["JAVA"] # 需要搜索的职位,会依次投递
  industry: ["不限"] #  "计算机软件", "计算机服务", "互联网" 公司行业，只能选三个，相关代码枚举的部分，如果需要其他的需要自己找
  cityCode: [ "上海"] # 只列举了部分,如果没有的需要自己找：目前支持的：全国 北京 上海 广州 深圳 成都
  experience: ["应届生"] # 工作经验："应届生", "在校生", "1-3年", "3-5年", "5-10年", "10年以上"
  jobType: "" #求职类型："全职", "兼职"
  salary: "" # 薪资（单选）："3K以下", "3-5K", "5-10K", "10-20K", "20-50K", "50K以上"
  degree: [""] # 学历: "初中及以下", "中专/中技", "高中", "大专", "本科", "硕士", "博士"
  scale: [ "不限" ] # 公司规模："0-20人", "20-99人", "100-499人", "500-999人", "1000-9999人", "10000人以上"
  stage: [ "不限" ] # "未融资", "天使轮", "A轮", "B轮", "C轮", "D轮及以上", "已上市", "不需要融资"

job51:
  #jobArea: [ "杭州","成都","武汉","南京","上海""深圳"]  #工作地区：目前只有【,"武汉","南京","成都","上海"】
  jobArea: [ "全国"]  #工作地区：目前只有【,"武汉","南京","成都","上海"】
  keywords: [ "测试"] #关键词：依次投递
  industry: [ "计算机软件", "计算机服务", "计算机硬件", "电信运营", "网络设备"]
  salary: [ "不限" ] #薪资范围：只能选5个【"2千以下", "2-3千", "3-4.5千", "4.5-6千", "6-8千", "0.8-1万", "1-1.5万", "1.5-2万", "2-3万", "3-4万", "4-5万", "5万以上"】
  workYear: ["在校生应届生"]
  degree: ["大专","本科"]

lagou:
  keywords: [ "自动化测试","测试开发","软件测试" ] #搜索关键词
  cityCode: "上海" #拉勾城市名没有限制,直接填写即可
  salary: "不限" #薪资【"不限","2k以下", "2k-5k", "5k-10k", "10k-15k", "15k-25k", "25k-50k", "50k以上"】
  scale: [ "不限" ] #公司规模【"不限","少于15人", "15-50人", "50-150人", "150-500人", "500-2000人", "2000人以上"】

liepin:
  cityCode: "全国" # 目前支 持的：全国 北京 上海 广州 深圳 成都
  keywords: [ "测试"]
  workYearCode: "实习生"
  salary: "" # 填 15$30 代表 15k-30k

zhilian:
  cityCode: "成都"
  salary: "不限" #薪资区间
  type: "校园"
  keywords: [ "软件测试","自动化测试","测试开发"]